export enum ErrorCode {
  // Auth & Security
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_REFRESH_REVOKED = "AUTH_REFRESH_REVOKED",
  AUTH_USER_DISABLED = "AUTH_USER_DISABLED",

  // Users & Roles
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",

  // Products & Categories
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_INACTIVE = "PRODUCT_INACTIVE",
  PRODUCT_SLUG_EXISTS = "PRODUCT_SLUG_EXISTS",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  CATEGORY_SLUG_EXISTS = "CATEGORY_SLUG_EXISTS",
  VARIANT_NOT_FOUND = "VARIANT_NOT_FOUND",

  // Cart & Checkout
  CART_NOT_FOUND = "CART_NOT_FOUND",
  CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND",
  INVALID_QUANTITY = "INVALID_QUANTITY",
  PRODUCT_OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK",
  FEATURE_DISABLED = "FEATURE_DISABLED",

  // Orders
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  ORDER_INVALID_STATUS = "ORDER_INVALID_STATUS",
  ORDER_ALREADY_PAID = "ORDER_ALREADY_PAID",
  ORDER_CANNOT_CANCEL = "ORDER_CANNOT_CANCEL",

  // Payments
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_NOT_VERIFIED = "PAYMENT_NOT_VERIFIED",
  PAYMENT_SIGNATURE_INVALID = "PAYMENT_SIGNATURE_INVALID",
  PAYMENT_AMOUNT_MISMATCH = "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_ALREADY_PROCESSED = "PAYMENT_ALREADY_PROCESSED",

  // Media
  MEDIA_UPLOAD_FAILED = "MEDIA_UPLOAD_FAILED",
  MEDIA_NOT_FOUND = "MEDIA_NOT_FOUND",
  MEDIA_IN_USE = "MEDIA_IN_USE",
  MEDIA_TYPE_NOT_ALLOWED = "MEDIA_TYPE_NOT_ALLOWED",
  MEDIA_SIZE_EXCEEDED = "MEDIA_SIZE_EXCEEDED",

  // CMS
  BLOG_POST_NOT_FOUND = "BLOG_POST_NOT_FOUND",
  CERTIFICATE_NOT_FOUND = "CERTIFICATE_NOT_FOUND",
  PAGE_NOT_FOUND = "PAGE_NOT_FOUND",

  // Contact
  CONTACT_RATE_LIMITED = "CONTACT_RATE_LIMITED",
  CONTACT_MESSAGE_NOT_FOUND = "CONTACT_MESSAGE_NOT_FOUND",

  // General & Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
