import { Product, Certificate, Article, BranchOffice, TeamMember } from '../types';

export const PRODUCTS: Product[] = [
  {
    id: 'sabo-milk-32',
    slug: 'sabo-pasterizatsiyalangan-sut-3-2',
    name: {
      uz: 'SABO Pasterizatsiyalangan Sut 3.2%',
      ru: 'SABO Пастеризованное молоко 3.2%',
      en: 'SABO Pasteurized Whole Milk 3.2%',
    },
    shortDescription: {
      uz: '1000g PET butilkada 100% tabiiy va yangi sog\'ilgan sigir suti.',
      ru: 'Молоко 3,2% марки SABO 1000гр в ПЭТ бутылках.',
      en: '100% natural fresh cow milk 3.2% in 1000g PET bottles.',
    },
    fullDescription: {
      uz: 'SABO 3.2% pasterizatsiyalangan suti — o\'z fermamizning toza tabiiy yaylovlarida parvarishlangan zotdor sigirlardan olingan. Yumshoq pasterizatsiya texnologiyasi orqali sut tarkibidagi barcha kalsiy, oqsillar va vitaminlar to\'liq saqlanib qoladi. Choy, kofe, bo\'tqalar va oilaviy nonushta uchun ayni muddao.',
      ru: 'Пастеризованное молоко SABO 3.2% получено от здоровых коров с собственных ферм. Бережная температурная обработка сохраняет природную пользу кальция, белков и витаминов. Прекрасно подходит для каш, кофе и выпечки.',
      en: 'SABO 3.2% pasteurized milk is sourced directly from healthy pasture-fed cows on certified farms. Gentle heat treatment preserves all natural calcium, essential proteins, and vitamins.',
    },
    category: 'milk',
    categoryLabel: {
      uz: 'Sut mahsulotlari',
      ru: 'Молоко',
      en: 'Fresh Milk',
    },
    images: [
      '/image/SaboSutim.jpg',
      '/image/Sabo_Milk.jpg',
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
    ],
    fatContent: '3.2%',
    volumeOptions: [
      { volume: '500 ml', price: 6000 },
      { volume: '1000 ml (1L)', price: 11000, isDefault: true },
      { volume: '1500 ml (1.5L)', price: 15500 },
    ],
    isOrganic: true,
    isBestseller: true,
    isNew: false,
    shelfLife: {
      uz: '7 kun (+2°C dan +4°C gacha)',
      ru: '7 суток (при t +2°C...+4°C)',
      en: '7 days (at +2°C to +4°C)',
    },
    storageConditions: {
      uz: '+2°C dan +4°C gacha haroratda sovutgichda saqlang. Ochilgandan so\'ng 48 soat ichida iste\'mol qiling.',
      ru: 'Хранить в холодильнике при t от +2°C до +4°C. После вскрытия употребить в течение 48 часов.',
      en: 'Store refrigerated at +2°C to +4°C. Consume within 48 hours after opening.',
    },
    ingredients: {
      uz: 'Faqat me\'yoriga keltirilgan tabiiy sigir suti.',
      ru: 'Нормализованное цельное коровье молоко высшего сорта.',
      en: '100% Normalized whole cows milk.',
    },
    nutrition: {
      calories: 59,
      proteins: 3.0,
      fats: 3.2,
      carbohydrates: 4.7,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol', 'Organic Standard'],
    rating: 4.9,
    reviewsCount: 168,
    inStock: true,
  },
  {
    id: 'sabo-kefir-1l',
    slug: 'sabo-an-anaviy-kefir-1l',
    name: {
      uz: 'SABO Kefir 1L (3.2%)',
      ru: 'SABO Кефир 1L (3.2%)',
      en: 'SABO Traditional Kefir 1L (3.2%)',
    },
    shortDescription: {
      uz: '1 litrlik PET butilkadagi me\'yorlashtirilgan tabiiy pasterizatsiyalangan kefir.',
      ru: 'Кефир пастеризованный, нормализованный, 3.2% в 1л ПЭТ бутылке.',
      en: 'Traditional pasteurized kefir 3.2% in 1L bottle.',
    },
    fullDescription: {
      uz: 'SABO Kefir 1L — tabiiy tirik zamburug\'lar (kefir achitqisi) bilan pasterizatsiyalangan, me\'yorlashtirilgan sigir sutidan tayyorlangan. Oshqozon-ichak mikroflorasini yaxshilaydi, yengil hazm bo\'ladi va immunitetni ko\'taradi.',
      ru: 'Кефир SABO 1L, пастеризованное, нормализованное коровье молоко. Массовая доля жира: 3.2%. 1 литрлик пет бутылкага қадоқланган.',
      en: 'SABO 1L Kefir is made from pasteurized, normalized cow milk with live symbiotic cultures to aid digestion and boost metabolism.',
    },
    category: 'kefir_yogurt',
    categoryLabel: {
      uz: 'Qatiq va Kefir',
      ru: 'Кефир и Йогурты',
      en: 'Kefir & Yogurt',
    },
    images: [
      '/image/Sabo_Kefir.jpg',
      '/image/Sabo_Kefir_05.jpg',
    ],
    fatContent: '3.2%',
    volumeOptions: [
      { volume: '1000 ml (1L)', price: 11000, isDefault: true },
    ],
    isOrganic: true,
    isBestseller: true,
    isNew: false,
    shelfLife: {
      uz: '10 kun (+2°C dan +4°C gacha)',
      ru: '10 суток (при t +2°C...+4°C)',
      en: '10 days (at +2°C to +4°C)',
    },
    storageConditions: {
      uz: '+2°C dan +4°C gacha haroratda saqlang.',
      ru: 'Хранить в холодильнике при температуре +2°C...+4°C.',
      en: 'Refrigerate between +2°C and +4°C.',
    },
    ingredients: {
      uz: 'Tabiiy pasterizatsiyalangan sigir suti, tirik kefir achitqisi.',
      ru: 'Молоко пастеризованное нормализованное, закваска на живых кефирных грибках.',
      en: 'Pasteurized normalized cows milk, live active kefir sourdough culture.',
    },
    nutrition: {
      calories: 56,
      proteins: 3.0,
      fats: 3.2,
      carbohydrates: 4.1,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 4.9,
    reviewsCount: 124,
    inStock: true,
  },
  {
    id: 'sabo-kefir-05',
    slug: 'sabo-kefir-0-5l',
    name: {
      uz: 'SABO Kefir 0.5L (3.2%)',
      ru: 'SABO Кефир 0.5L (3.2%)',
      en: 'SABO Kefir 0.5L (3.2%)',
    },
    shortDescription: {
      uz: '0.5 litrlik ixcham PET butilkadagi toza pasterizatsiyalangan kefir.',
      ru: 'Кефир пастеризованный, нормализованный 3.2% в 0.5л бутылке.',
      en: 'Compact 0.5L pasteurized kefir bottle for quick healthy hydration.',
    },
    fullDescription: {
      uz: 'SABO 0.5L Kefir — har kuni olib yurish va kun davomida tetiklashish uchun qulay o\'lchamdagi toza sigir suti kefiri. Tirik probiotiklarga boy, oshqozon faoliyatini normallashtiradi.',
      ru: 'Кефир SABO 0.5L, пастеризованное, нормализованное. Массовая доля жира: 3.2%, Вид молока: коровье. 0.5 литрлик пет бутылкага қадоқланган.',
      en: 'SABO 0.5L Kefir provides daily gut support in a convenient travel-friendly format made from whole dairy.',
    },
    category: 'kefir_yogurt',
    categoryLabel: {
      uz: 'Qatiq va Kefir',
      ru: 'Кефир и Йогурты',
      en: 'Kefir & Yogurt',
    },
    images: [
      '/image/Sabo_Kefir_05.jpg',
      '/image/Sabo_Kefir.jpg',
    ],
    fatContent: '3.2%',
    volumeOptions: [
      { volume: '500 ml (0.5L)', price: 5000, isDefault: true },
    ],
    isOrganic: true,
    isBestseller: false,
    isNew: true,
    shelfLife: {
      uz: '10 kun (+2°C dan +4°C gacha)',
      ru: '10 суток (при t +2°C...+4°C)',
      en: '10 days (at +2°C to +4°C)',
    },
    storageConditions: {
      uz: '+2°C dan +4°C gacha haroratda saqlang.',
      ru: 'Хранить в холодильнике при температуре +2°C...+4°C.',
      en: 'Refrigerate between +2°C and +4°C.',
    },
    ingredients: {
      uz: 'Pasterizatsiyalangan toza sigir suti, kefir achitqisi.',
      ru: 'Молоко коровье нормализованное, закваска.',
      en: 'Normalized whole cow milk, kefir sourdough.',
    },
    nutrition: {
      calories: 56,
      proteins: 3.0,
      fats: 3.2,
      carbohydrates: 4.1,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 4.8,
    reviewsCount: 89,
    inStock: true,
  },
  {
    id: 'sabo-yogurt-05',
    slug: 'sabo-mevali-yogurt-0-5l',
    name: {
      uz: 'SABO Mevali Yogurt 0.5L',
      ru: 'SABO Йогурт фруктовый 0.5L',
      en: 'SABO Fruit Yogurt 0.5L',
    },
    shortDescription: {
      uz: '100% tabiiy mevalar va yangi sutdan tayyorlangan yoqimli desert yogurt.',
      ru: 'Йогурты SABO изготовлены из 100% натуральных фруктов и свежего молока.',
      en: 'Delicious fruit drinking yogurt crafted from pure dairy and real fruits.',
    },
    fullDescription: {
      uz: 'SABO mevali yogurtlari 100% tabiiy mevalar va yangi sog\'ilgan sigir sutidan tayyorlangan. Hech qanday sun\'iy bo\'yoq yoki kimyoviy quyultiruvchilarsiz. Shirin, yoqimli va bolajonlar uchun nihoyatda foydali.',
      ru: 'Йогурты SABO изготовлены из 100% натуральных фруктов. О качестве и вкусе вообще сказать нечего — исключительно натурально и полезно.',
      en: 'SABO Fruit Yogurt blends farm-fresh milk with real sun-ripened fruits. Free from artificial dyes and harsh additives.',
    },
    category: 'desserts',
    categoryLabel: {
      uz: 'Desertlar va Yogurt',
      ru: 'Йогурты и Десерты',
      en: 'Desserts & Curd',
    },
    images: [
      '/image/Sabo_Yogurt.jpg',
      'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
    ],
    fatContent: '2.5%',
    volumeOptions: [
      { volume: '500 ml', price: 10000, isDefault: true },
    ],
    isOrganic: true,
    isBestseller: true,
    isNew: true,
    shelfLife: {
      uz: '14 kun (+2°C dan +4°C gacha)',
      ru: '14 суток (+2°C...+4°C)',
      en: '14 days (at +2°C to +4°C)',
    },
    storageConditions: {
      uz: '+2°C dan +4°C gacha sovutgichda saqlang.',
      ru: 'Хранить в холодильнике при +2°C...+4°C.',
      en: 'Keep refrigerated at +2°C to +4°C.',
    },
    ingredients: {
      uz: 'Tabiiy sigir suti, mevali tabiiy bo\'tqa, tirik yogurt achitqisi.',
      ru: 'Молоко нормализованное, фруктовый наполнитель, закваска йогуртовая.',
      en: 'Normalized cow milk, natural fruit puree, live yogurt ferment.',
    },
    nutrition: {
      calories: 78,
      proteins: 3.2,
      fats: 2.5,
      carbohydrates: 11.5,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 4.9,
    reviewsCount: 115,
    inStock: true,
  },
  {
    id: 'sabo-smetana-20',
    slug: 'sabo-smetana-20-foiz',
    name: {
      uz: 'SABO Smetana 20% (400g / 200g)',
      ru: 'SABO Сметана 20% (400г / 200г)',
      en: 'SABO Sour Cream 20% (400g / 200g)',
    },
    shortDescription: {
      uz: 'Qalin, mayin va tabiiy qaymoqli 20% li smetana.',
      ru: 'Сметана SABO м.д.ж. 20% 400/200 гр. в фирменном стакане.',
      en: 'Rich, velvety 20% traditional sour cream in 400g and 200g cups.',
    },
    fullDescription: {
      uz: 'SABO 20% li smetanasi — pasterizatsiyalangan toza qaymoq va maxsus sut kislotali bakteriyalar yordamida tayyorlangan. Quyuq konsistensiya, mayin nordon-shirin ta\'m va yengil hazm bo\'lish xususiyatiga ega. Sho\'rvalar, somsa va salatlar uchun ideal.',
      ru: 'SABO Сметана м.д.ж. 20% 400/200 гр. стакан. Предоставлен сертификат соответствия. Наличие штрих-кода на этикетке. Изготовлена из чистых сливок.',
      en: 'SABO 20% sour cream is crafted from pasteurized dairy cream and select starter cultures, delivering a velvety texture and rich culinary depth.',
    },
    category: 'sourcream_butter',
    categoryLabel: {
      uz: 'Qaymoq va Smetana',
      ru: 'Сметана и Масло',
      en: 'Sour Cream & Butter',
    },
    images: [
      '/image/Sabo_Smetana.jpg',
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
    ],
    fatContent: '20%',
    volumeOptions: [
      { volume: '200 g', price: 6000 },
      { volume: '400 g', price: 10000, isDefault: true },
    ],
    isOrganic: true,
    isBestseller: true,
    isNew: false,
    shelfLife: {
      uz: '14 kun (+2°C dan +4°C gacha)',
      ru: '14 суток (+2°C...+4°C)',
      en: '14 days (+2°C to +4°C)',
    },
    storageConditions: {
      uz: '+2°C dan +4°C gacha sovutgichda saqlang.',
      ru: 'Хранить в холодильнике при +2°C...+4°C.',
      en: 'Keep refrigerated between +2°C and +4°C.',
    },
    ingredients: {
      uz: 'Pasterizatsiyalangan tabiiy qaymoq, sut kislotali achitqi.',
      ru: 'Сливки пастеризованные, закваска чистых культур молочнокислых бактерий.',
      en: 'Pasteurized dairy cream, select lactic acid starter culture.',
    },
    nutrition: {
      calories: 206,
      proteins: 2.5,
      fats: 20.0,
      carbohydrates: 3.4,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 4.9,
    reviewsCount: 154,
    inStock: true,
  },
  {
    id: 'sabo-qaymoq-200',
    slug: 'sabo-tabiiy-qaymoq-200g',
    name: {
      uz: 'SABO Qaymoq 200g',
      ru: 'SABO Каймак / Сливки 200г',
      en: 'SABO Fresh Clotted Cream (Qaymoq) 200g',
    },
    shortDescription: {
      uz: 'Maxsus 200g idishga qadoqlangan toza, qaymoqli va xushbo\'y milliy qaymoq.',
      ru: 'Продукт Каймок SABO, чистый, отличного качества в контейнерах по 200 гр.',
      en: 'Traditional clotted cream packed in fresh 200g containers.',
    },
    fullDescription: {
      uz: 'SABO Qaymoq 200g — an\'anaviy usulda sog\'ilgan toza sutdan ajratib olingan quyuq, boy va xushbo\'y qaymoq. Nonushtada issiq non, asal yoki murabbo bilan ajoyib uyg\'unlashadi.',
      ru: 'Продукт Каймок SABO, чистый, хорошего качества, пригоден для употребления, расфасован в контейнеры по 200 гр. Нежнейший традиционный вкус.',
      en: 'SABO Traditional Qaymoq (clotted cream) offers an authentic sweet cream richness, ideal for morning bread, honey and tea.',
    },
    category: 'sourcream_butter',
    categoryLabel: {
      uz: 'Qaymoq va Sariyog\'',
      ru: 'Сметана и Масло',
      en: 'Sour Cream & Butter',
    },
    images: [
      '/image/Sabo_Qaymoq.jpg',
      'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=800&q=80',
    ],
    fatContent: '45%',
    volumeOptions: [
      { volume: '200 g', price: 10000, isDefault: true },
      { volume: '400 g', price: 19000 },
    ],
    isOrganic: true,
    isBestseller: true,
    isNew: false,
    shelfLife: {
      uz: '10 kun (+2°C dan +4°C gacha)',
      ru: '10 суток (+2°C...+4°C)',
      en: '10 days (at +2°C to +4°C)',
    },
    storageConditions: {
      uz: '+2°C dan +4°C gacha haroratda sovutgichda saqlang.',
      ru: 'Хранить в холодильнике при +2°C...+4°C.',
      en: 'Store refrigerated at +2°C to +4°C.',
    },
    ingredients: {
      uz: '100% tabiiy pasterizatsiyalangan sigir qaymog\'i.',
      ru: '100% натуральные пастеризованные коровьи сливки.',
      en: '100% pure pasteurized dairy cream.',
    },
    nutrition: {
      calories: 420,
      proteins: 2.1,
      fats: 45.0,
      carbohydrates: 2.8,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 5.0,
    reviewsCount: 192,
    inStock: true,
  },
  {
    id: 'sabo-butter-825',
    slug: 'sabo-premium-sariyog-82-5',
    name: {
      uz: 'SABO Tabiiy Sariyog\' 82.5%',
      ru: 'SABO Масло сливочное Традиционное 82.5%',
      en: 'SABO Traditional Creamery Butter 82.5%',
    },
    shortDescription: {
      uz: 'Faqat toza tabiiy qaymoqdan tayyorlangan oliy navli sariyog\'.',
      ru: 'Высший сорт из чистых пастеризованных сливок. Нежнейший сливочный вкус.',
      en: 'Premium grade butter made exclusively from freshly separated sweet cream.',
    },
    fullDescription: {
      uz: 'SABO 82.5% an\'anaviy sariyog\' — faqat toza pasterizatsiyalangan qaymoqni urish orqali tayyorlanadi. O\'simlik yog\'lari (palma yog\'i), bo\'yoqlar va sun\'iy ta\'m beruvchilar mutlaqo yo\'q. Non ustiga surtish, nonushta va premium pishiriqlar uchun beqiyos.',
      ru: 'Сливочное масло SABO 82.5% изготавливается методом взбивания свежих натуральных сливок. 0% растительных жиров, консервантов и красителей.',
      en: 'SABO 82.5% traditional butter is churned from fresh sweet pasture cream. Melt-in-mouth texture, golden sheen, and natural sweetness without any vegetable oils or palm fat.',
    },
    category: 'sourcream_butter',
    categoryLabel: {
      uz: 'Qaymoq va Sariyog\'',
      ru: 'Сметана и Масло',
      en: 'Sour Cream & Butter',
    },
    images: [
      'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589985270958-af087799cf16?auto=format&fit=crop&w=800&q=80',
    ],
    fatContent: '82.5%',
    volumeOptions: [
      { volume: '200 g', price: 24000, isDefault: true },
      { volume: '400 g', price: 46000 },
      { volume: '1000 g', price: 110000 },
    ],
    isOrganic: true,
    isBestseller: true,
    isNew: false,
    shelfLife: {
      uz: '30 kun (+2°C dan +4°C) / 120 kun (-18°C da)',
      ru: '30 суток (+2°C...+4°C) / 120 суток (-18°C)',
      en: '30 days (+2°C to +4°C) / 120 days (-18°C)',
    },
    storageConditions: {
      uz: 'Qorong\'i va sovuq joyda saqlang.',
      ru: 'Хранить в холодильнике или морозильной камере.',
      en: 'Keep refrigerated or frozen in a dry cool space.',
    },
    ingredients: {
      uz: '100% pasterizatsiyalangan tabiiy qaymoq.',
      ru: 'Сливки пастеризованные из коровьего молока.',
      en: '100% pasteurized fresh dairy cream.',
    },
    nutrition: {
      calories: 748,
      proteins: 0.6,
      fats: 82.5,
      carbohydrates: 0.8,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 4.9,
    reviewsCount: 118,
    inStock: true,
  },
  {
    id: 'sabo-cheese-gauda',
    slug: 'sabo-tabiiy-pishloq-gauda-45',
    name: {
      uz: 'SABO Gauda Pishlog\'i 45%',
      ru: 'SABO Сыр Гауда Натуральный 45%',
      en: 'SABO Artisan Gouda Cheese 45%',
    },
    shortDescription: {
      uz: 'Kamida 60 kun yetiltirilgan oliy sifatli yarim qattiq pishloq.',
      ru: 'Полутвердый сыр естественного созревания не менее 60 дней.',
      en: 'Premium semi-hard cheese naturally aged for minimum 60 days.',
    },
    fullDescription: {
      uz: 'SABO Gauda pishlog\'i Gollandiya texnologiyasi asosida toza sigir sutidan tayyorlanadi. 2 oy davomida maxsus mikroiqlimli omborlarda pishib yetiladi. Mayin yong\'oqsimon xushbo\'ylik va eruvchan nozik tuzilish.',
      ru: 'Сыр Гауда SABO производится по голландской рецептуре из отборного молока. Выдерживается 60 дней. Обладает мягким сливочно-ореховым послевкусием.',
      en: 'SABO Gouda is crafted according to traditional Dutch methods from rich whole milk, cellared for 60 days to develop subtle nutty notes and smooth texture.',
    },
    category: 'cheese',
    categoryLabel: {
      uz: 'Pishloqlar',
      ru: 'Сыры',
      en: 'Natural Cheeses',
    },
    images: [
      'https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=800&q=80',
    ],
    fatContent: '45%',
    volumeOptions: [
      { volume: '250 g', price: 28000, isDefault: true },
      { volume: '500 g', price: 54000 },
      { volume: '1000 g', price: 105000 },
    ],
    isOrganic: true,
    isBestseller: false,
    isNew: true,
    shelfLife: {
      uz: '90 kun (+2°C dan +6°C gacha)',
      ru: '90 суток (при t +2°C...+6°C)',
      en: '90 days (at +2°C to +6°C)',
    },
    storageConditions: {
      uz: 'Sovutgichda quruq holda saqlang.',
      ru: 'Хранить в холодильнике в сухом месте.',
      en: 'Keep refrigerated in a dry compartment.',
    },
    ingredients: {
      uz: 'Pasterizatsiyalangan sigir suti, sut achituvchi fermentlar, osh tuzi.',
      ru: 'Молоко коровье пастеризованное, молокосвертывающий фермент, соль поваренная.',
      en: 'Pasteurized cow milk, microbial rennet enzyme, salt.',
    },
    nutrition: {
      calories: 356,
      proteins: 25.0,
      fats: 27.5,
      carbohydrates: 1.2,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 4.8,
    reviewsCount: 76,
    inStock: true,
  },
  {
    id: 'sabo-tvorog-9',
    slug: 'sabo-donador-tvorog-9',
    name: {
      uz: 'SABO Donador Tvorog 9%',
      ru: 'SABO Творог Рассыпчатый 9%',
      en: 'SABO Granular Cottage Cheese 9%',
    },
    shortDescription: {
      uz: 'Oqsil va kalsiyga boy, mayin donador klassik tvorog.',
      ru: 'Богат натуральным белком и кальцием. Идеально для сырников и завтрака.',
      en: 'Protein-packed granular cottage cheese made from fresh whole milk.',
    },
    fullDescription: {
      uz: 'SABO 9% donador tvorog — an\'anaviy ivitish usulida tayyorlangan. Quruq va nordon emas, aksincha xushxo\'r qaymoqli ta\'mga ega. Sportchilar, bolalar va pishiriq ishqibozlari uchun ideal oqsil manbai.',
      ru: 'Рассыпчатый творог SABO 9% с нежной сливочной текстурой. Источник легкоусвояемого белка (казеина) и фосфора.',
      en: 'SABO 9% granular curd is made using gentle coagulation, resulting in soft, moist curds bursting with calcium and slow-digesting casein protein.',
    },
    category: 'desserts',
    categoryLabel: {
      uz: 'Desertlar va Tvorog',
      ru: 'Творог и Десерты',
      en: 'Desserts & Curd',
    },
    images: [
      'https://images.unsplash.com/photo-1559598467-f8b76c8155d0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=800&q=80',
    ],
    fatContent: '9.0%',
    volumeOptions: [
      { volume: '250 g', price: 12000 },
      { volume: '400 g', price: 18500, isDefault: true },
      { volume: '1000 g', price: 44000 },
    ],
    isOrganic: true,
    isBestseller: true,
    isNew: false,
    shelfLife: {
      uz: '7 kun (+2°C dan +4°C gacha)',
      ru: '7 суток (+2°C...+4°C)',
      en: '7 days (+2°C to +4°C)',
    },
    storageConditions: {
      uz: '+2°C dan +4°C gacha sovutgichda saqlang.',
      ru: 'Хранить в холодильнике при +2°C...+4°C.',
      en: 'Store refrigerated at +2°C to +4°C.',
    },
    ingredients: {
      uz: 'Pasterizatsiyalangan me\'yorlashtirilgan sut, tirik achitqi.',
      ru: 'Молоко коровье пастеризованное, закваска творожная.',
      en: 'Pasteurized normalized milk, live active culture.',
    },
    nutrition: {
      calories: 159,
      proteins: 16.0,
      fats: 9.0,
      carbohydrates: 3.0,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 4.9,
    reviewsCount: 148,
    inStock: true,
  },
  {
    id: 'sabo-lactose-free',
    slug: 'sabo-laktozasiz-sut-1-5',
    name: {
      uz: 'SABO Laktozasiz Sut 1.5%',
      ru: 'SABO Безлактозное молоко 1.5%',
      en: 'SABO Lactose-Free Milk 1.5%',
    },
    shortDescription: {
      uz: 'Laktoza sezgirligi bo\'lganlar uchun 100% yengil hazm bo\'luvchi sut.',
      ru: 'Легкое усвоение для людей с непереносимостью лактозы.',
      en: '100% easily digestible milk specially formulated for lactose sensitivity.',
    },
    fullDescription: {
      uz: 'SABO Laktozasiz sut — maxsus tabiiy laktaza fermenti yordamida laktozasi glyukoza va galaktozaga parchalangan. Shirinroq tabiiy ta\'mga ega va hech qanday oshqozon noqulayligini keltirib chiqarmaydi.',
      ru: 'Безлактозное молоко SABO 1.5% расщеплено натуральным ферментом лактазой. Обладает приятным сладковатым вкусом и сохраняет всю пользу свежего молока.',
      en: 'SABO Lactose-Free 1.5% milk undergoes enzymatic micro-filtration, breaking down complex milk sugar for optimal digestion without losing any calcium.',
    },
    category: 'milk',
    categoryLabel: {
      uz: 'Sut mahsulotlari',
      ru: 'Молоко',
      en: 'Fresh Milk',
    },
    images: [
      '/image/SaboSutim.jpg',
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
    ],
    fatContent: '1.5%',
    volumeOptions: [
      { volume: '1000 ml', price: 13500, isDefault: true },
    ],
    isLactoseFree: true,
    isOrganic: true,
    isBestseller: false,
    isNew: true,
    shelfLife: {
      uz: '14 kun (+2°C dan +4°C gacha)',
      ru: '14 суток (+2°C...+4°C)',
      en: '14 days (+2°C to +4°C)',
    },
    storageConditions: {
      uz: '+2°C dan +4°C gacha sovutgichda saqlang.',
      ru: 'Хранить в холодильнике при +2°C...+4°C.',
      en: 'Store refrigerated at +2°C to +4°C.',
    },
    ingredients: {
      uz: 'Me\'yorlashtirilgan sut, laktaza fermenti.',
      ru: 'Молоко нормализованное, фермент лактаза.',
      en: 'Normalized cow milk, natural lactase enzyme.',
    },
    nutrition: {
      calories: 44,
      proteins: 3.0,
      fats: 1.5,
      carbohydrates: 4.7,
    },
    certifications: ['ISO 9001', 'HACCP', 'Halol'],
    rating: 4.8,
    reviewsCount: 82,
    inStock: true,
  },
];

export const CERTIFICATES: Certificate[] = [
  {
    id: 'cert-iso-9001',
    title: 'ISO 9001:2015 Xalqaro Sifat Menejmenti',
    code: 'ISO-9001:2015-PM-UZ',
    badge: {
      uz: 'Sifat Menejmenti',
      ru: 'Менеджмент Качества',
      en: 'Quality Management',
    },
    issueDate: '2024-03-15',
    issuer: 'SGS International Certification Services',
    description: {
      uz: 'SABO korxonasining butun ishlab chiqarish, qabul qilish va xomashyo nazorati jarayonlari xalqaro ISO 9001 talablariga to\'liq muvofiq deb topildi.',
      ru: 'Сертификат подтверждает полное соответствие системы менеджмента качества SABO мировым стандартам ISO 9001:2015.',
      en: 'Confirms that the production, raw intake, and lab protocols of SABO fully conform to the ISO 9001:2015 standard.',
    },
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    pdfUrl: '#',
  },
  {
    id: 'cert-haccp',
    title: 'HACCP (ISO 22000:2018) Oziq-ovqat Xavfsizligi',
    code: 'HACCP-22000-PM-UZ',
    badge: {
      uz: 'Oziq-ovqat Xavfsizligi',
      ru: 'Пищевая Безопасность',
      en: 'Food Safety System',
    },
    issueDate: '2024-05-10',
    issuer: 'TÜV Rheinland Group',
    description: {
      uz: 'Sutni sog\'ishdan to tayyor mahsulotni mijozga yetkazguncha bo\'lgan barcha kritik nazorat nuqtalari (CCP) qat\'iy avtomatik monitoring qilinadi.',
      ru: 'Сертификат безопасности пищевой продукции гарантирует строгий контроль на всех этапах от фермы до полки.',
      en: 'Hazard Analysis Critical Control Point certification guaranteeing zero contamination risks throughout the dairy cold chain.',
    },
    image: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    pdfUrl: '#',
  },
  {
    id: 'cert-halol',
    title: 'Halol (Halal Standard) Sertifikati',
    code: 'HALAL-UZ-2024-089',
    badge: {
      uz: '100% Halol',
      ru: '100% Халяль',
      en: '100% Halal Certified',
    },
    issueDate: '2024-01-20',
    issuer: 'O\'zbekiston Musulmonlari Idorasi & Halal Center',
    description: {
      uz: 'Barcha SABO mahsulotlari tarkibi, achitqilari va ishlab chiqarish gigiyenasi Halol talablariga 100% mosligi tasdiqlangan.',
      ru: 'Вся продукция SABO, закваски и технологические процессы полностью соответствуют каноническим нормам Халяль.',
      en: 'Certifies that all SABO dairy products, bacterial ferments and manufacturing hygiene strictly meet global Halal standards.',
    },
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80',
    pdfUrl: '#',
  },
];

export const ARTICLES: Article[] = [
  {
    id: 'art-1',
    slug: 'tabiiy-sutning-immunitetdagi-orni',
    category: 'news',
    title: {
      uz: 'Tabiiy pasterizatsiyalangan sutning inson immunitetidagi o\'rni',
      ru: 'Роль натурального пастеризованного молока в укреплении иммунитета',
      en: 'The Vital Role of Fresh Pasteurized Milk in Boosting Immunity',
    },
    excerpt: {
      uz: 'Nima uchun yumshoq haroratda pasterizatsiya qilingan tabiiy sigir suti qishki va bahorgi mavsumda organizmning asosiy himoyachisi hisoblanadi?',
      ru: 'Почему щадящая пастеризация сохраняет биоактивные свойства белков и кальция в межсезонье?',
      en: 'Why gently pasteurized fresh whole milk serves as an essential nutritional fortress during transitional seasons?',
    },
    content: {
      uz: 'Sut — inson organizmi uchun zarur bo\'lgan 20 dan ortiq aminokislotalar, oson o\'zlashuvchi kalsiy, fosfor, D va B12 vitaminlarining boy manbaidir. SABO da qo\'llaniladigan 74-76°C li pasterizatsiya texnologiyasi sutning oqsil strukturasini buzmasdan, barcha tabiiy xususiyatlarini saqlab qoladi.',
      ru: 'Молоко — источник более 20 аминокислот, легкоусвояемого кальция, фосфора, витаминов D и B12. Технология SABO при 74-76°C сохраняет естественную пользу без разрушения белковой структуры.',
      en: 'Milk supplies over 20 essential amino acids, highly bioavailable calcium, phosphorus, vitamins D and B12. SABO gentle pasteurization preserves bioactive integrity.',
    },
    date: '14-fevral, 2026',
    image: '/image/SaboSutim.jpg',
    readTime: '4 daqiqa',
    author: 'Dr. Shahnoza Alimova, Nutrisiolog',
  },
  {
    id: 'art-2',
    slug: 'sabo-smetanasi-bilan-mazzali-pishiriqlar',
    category: 'recipes',
    title: {
      uz: 'SABO 20% smetanasi bilan mayin tvorogli pirog retsepti',
      ru: 'Рецепт нежнейшего творожного пирога со сметаной SABO 20%',
      en: 'Delicate Cottage Cheese Pie Recipe with SABO 20% Sour Cream',
    },
    excerpt: {
      uz: 'Oilaviy choy dasturxoni uchun 30 daqiqada tayyor bo\'ladigan og\'izda eriydigan smetanali-tvorogli ajoyib pishiriq.',
      ru: 'Быстрый и невероятно нежный домашний пирог к чаю за 30 минут из свежих молочных продуктов SABO.',
      en: 'Mouthwatering 30-minute homemade tea pie recipe crafted with fresh SABO sour cream and curd.',
    },
    content: {
      uz: 'Tvorogli pirog tayyorlash uchun SABO 9% donador tvorogi va SABO 20% smetanasini blenderda mayin qaymoq holatiga keltiring. Tuxum va ozgina tabiiy asal qo\'shib, 180°C haroratda 25 daqiqa pishiring.',
      ru: 'Для приготовления взбейте блендером творог SABO 9% и сметану SABO 20% до кремовой текстуры. Добавьте яйца и выпекайте при 180°C 25 минут.',
      en: 'Blend SABO 9% curd with SABO 20% sour cream until creamy. Fold in eggs and natural honey, bake at 180°C for 25 minutes.',
    },
    date: '10-fevral, 2026',
    image: '/image/Sabo_Smetana.jpg',
    readTime: '6 daqiqa',
    author: 'Madina Rustamova, Fud-bloger',
    recipeIngredients: {
      uz: [
        'SABO 9% Donador Tvorogi — 400g',
        'SABO 20% Smetanasi — 150g',
        'SABO 82.5% Sariyog\'i — 50g',
        'Tuxum — 3 dona',
        'Shakar yoki Asal — 80g',
        'Vanil va limon sedrasi',
      ],
      ru: [
        'Творог SABO 9% — 400г',
        'Сметана SABO 20% — 150г',
        'Сливочное масло SABO 82.5% — 50г',
        'Яйца — 3 шт',
        'Сахар или мед — 80г',
        'Ванилин и цедра лимона',
      ],
      en: [
        'SABO 9% Cottage Cheese — 400g',
        'SABO 20% Sour Cream — 150g',
        'SABO 82.5% Butter — 50g',
        'Eggs — 3 pcs',
        'Sugar or honey — 80g',
        'Vanilla & lemon zest',
      ],
    },
  },
  {
    id: 'art-3',
    slug: 'kefir-ichishning-5-oltin-qoidasi',
    category: 'news',
    title: {
      uz: 'Kechqurun kefir ichishning salomatlik uchun 5 ta isbotlangan foydasi',
      ru: '5 доказанных преимуществ стакана кефира перед сном',
      en: '5 Proven Health Benefits of Drinking Kefir Before Sleep',
    },
    excerpt: {
      uz: 'Har kuni uxlashdan 1 soat oldin bir stakan SABO kefiri ichish oshqozon-ichak va asab tizimiga qanday ta\'sir qiladi?',
      ru: 'Как ежедневный стакан натурального кефира SABO нормализует сон и восстанавливает микробиоту?',
      en: 'How a single glass of fresh SABO probiotic kefir at bedtime calms the nervous system and repairs digestion.',
    },
    content: {
      uz: 'Tirik kefir zamburug\'lari kechasi uyqu paytida oshqozon-ichak traktida faol probiotik muhit hosil qiladi. Shuningdek, tarkibidagi triptofan aminokislotasi uyqu sifatini chuqurlashtiradi.',
      ru: 'Живые кефирные грибки ночью активно восстанавливают микрофлору, а аминокислота триптофан способствует глубокому и спокойному сну.',
      en: 'Live kefir symbiotes rebuild digestive flora overnight while tryptophan gently enhances sleep quality.',
    },
    date: '02-fevral, 2026',
    image: '/image/Sabo_Kefir.jpg',
    readTime: '5 daqiqa',
    author: 'Dr. Jasur Mansurov, Gastroenterolog',
  },
];

export const BRANCHES: BranchOffice[] = [
  {
    id: 'branch-hq',
    city: {
      uz: 'Toshkent shahri (Bosh ofis & Zavod)',
      ru: 'г. Ташкент (Головной офис и Завод)',
      en: 'Tashkent City (HQ & Production Facility)',
    },
    address: {
      uz: 'Yangihayot tumani, Yangi Choshtepa ko\'chasi, 45-uy',
      ru: 'Янгихаётский р-н, ул. Янги Чоштепа, 45',
      en: '45 Yangi Choshtepa Str., Yangihayot district, Tashkent',
    },
    phone: '+998 (99) 345-16-55',
    email: 'info@sabo.uz',
    workingHours: {
      uz: 'Dushanba - Shanba: 08:00 - 20:00 (Yakshanba: 09:00 - 18:00)',
      ru: 'Пн - Сб: 08:00 - 20:00 (Вс: 09:00 - 18:00)',
      en: 'Mon - Sat: 08:00 - 20:00 (Sun: 09:00 - 18:00)',
    },
    coordinates: {
      lat: 41.2234,
      lng: 69.2156,
    },
    isHeadquarter: true,
  },
  {
    id: 'branch-samarkand',
    city: {
      uz: 'Samarqand shahri (Mintaqaviy markaz)',
      ru: 'г. Самарканд (Региональный центр)',
      en: 'Samarkand City (Regional Hub)',
    },
    address: {
      uz: 'Spitamen shoh ko\'chasi, 112-uy',
      ru: 'ул. Спитамена, 112',
      en: '112 Spitamen Ave., Samarkand',
    },
    phone: '+998 (99) 345-16-55',
    email: 'samarkand@sabo.uz',
    workingHours: {
      uz: 'Dushanba - Shanba: 08:30 - 19:00',
      ru: 'Пн - Сб: 08:30 - 19:00',
      en: 'Mon - Sat: 08:30 - 19:00',
    },
    coordinates: {
      lat: 39.6542,
      lng: 66.9597,
    },
  },
];

export const TESTIMONIALS = [
  {
    id: 't-1',
    authorName: 'Nodira Azimova',
    authorRole: '3 farzand onasi, Toshkent',
    rating: 5,
    date: '12-fevral, 2026',
    verifiedBuyer: true,
    comment: {
      uz: 'Farzandlarimga faqat SABO sutini beraman. Ta\'mi juda toza, qaymoqli va sun\'iy hid yo\'q. Ayniqsa 3.2% suti va smetanasi bizning oilaviy sevimlimiz!',
      ru: 'Покупаю для детей только SABO. Вкус очень натуральный, без посторонних запахов. Сметана 20% и молоко просто идеальны!',
      en: 'I exclusively choose SABO for my children. Taste is exceptionally pure and fresh. The sour cream and whole milk are daily staples in our household!',
    },
  },
  {
    id: 't-2',
    authorName: 'Jamoliddin Zokirov',
    authorRole: '"Chustiy Cuisine" Bosh oshpazi',
    rating: 5,
    date: '05-fevral, 2026',
    verifiedBuyer: true,
    comment: {
      uz: 'Restoranimiz pishiriqlari va xachapurilari uchun SABO qaymog\'i va sariyog\'idan foydalanamiz. Sifati doimiy bir xil va yuqori darajada.',
      ru: 'Для выпечки в нашем ресторане используем каймак и сливочное масло SABO. Качество всегда на высоте.',
      en: 'We source SABO butter and qaymoq for our restaurant bakery. The melt texture, aroma, and fat consistency are outstanding.',
    },
  },
];

export const FAQS = [
  {
    id: 'faq-1',
    question: {
      uz: 'SABO suti qanday pasterizatsiya qilinadi?',
      ru: 'Как пастеризуется молоко SABO?',
      en: 'How is SABO fresh milk pasteurized?',
    },
    answer: {
      uz: 'Biz past haroratli yumshoq pasterizatsiya usulidan (74-76°C) foydalanamiz. Bu zararli bakteriyalarni butunlay yo\'qotadi, ammo sutdagi barcha tabiiy kalsiy, oqsillar va vitaminlar saqlanib qoladi.',
      ru: 'Мы применяем щадящую бережную пастеризацию при 74-76°C, что уничтожает микробы, но сохраняет естественные витамины и структуру белка.',
      en: 'We use gentle, low-temperature pasteurization (74-76°C) which ensures 100% microbial safety while retaining natural calcium, proteins, and active enzymes.',
    },
  },
  {
    id: 'faq-2',
    question: {
      uz: 'Yetkazib berish va Telegram orqali buyurtma qanday ishlaydi?',
      ru: 'Как работает доставка и заказ через Telegram?',
      en: 'How does express delivery and Telegram ordering work?',
    },
    answer: {
      uz: 'Saytimiz orqali yoki Telegram (@SaboMilk / +998 99 345-16-55) orqali buyurtma berishingiz mumkin. Toshkent bo\'ylab sovutilgan transportda tezkor yetkaziladi.',
      ru: 'Вы можете оформить заказ на сайте или через Telegram (@SaboMilk / +998 99 345-16-55). Доставка осуществляется на специализированных рефрижераторах.',
      en: 'You can place orders on the website or via Telegram (@SaboMilk / +998 99 345-16-55). Fast refrigerated delivery across Tashkent.',
    },
  },
  {
    id: 'faq-3',
    question: {
      uz: 'Mahsulotlarda konservant yoki kukun suti bormi?',
      ru: 'Содержат ли продукты консерванты или сухое молоко?',
      en: 'Do your products contain preservatives or powdered milk?',
    },
    answer: {
      uz: 'Mutlaqo yo\'q! SABO ning asosiy shiori — "Tabiiylik sari intilamiz". Mahsulotlarimizda quruq kukun, palma yog\'i, sun\'iy bo\'yoq yoki kimyoviy konservantlar umuman ishlatilmaydi.',
      ru: 'Категорически нет! Главный девиз SABO — "Стремимся к натуральности". В составе только 100% свежее коровье молоко без сухого порошка и растительных жиров.',
      en: 'Never! SABO pledges 100% pure cow milk and live starter ferments. Zero powdered milk, zero palm oil, zero chemical additives.',
    },
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'team-1',
    name: 'Dilshod Rahmatov',
    role: {
      uz: 'Bosh Texnolog & Sifat Nazoratchisi',
      ru: 'Главный технолог и контролер качества',
      en: 'Chief Dairy Technologist & Quality Lead',
    },
    bio: {
      uz: 'Sut sanoatida 18 yillik xalqaro tajribaga ega. Germaniya va Niderlandiya sut zavodlarida malaka oshirgan.',
      ru: '18 лет опыта в молочной отрасли. Стажировался на ведущих предприятиях Германии и Нидерландов.',
      en: '18 years of dairy processing expertise with certifications from Germany and Netherlands.',
    },
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'team-2',
    name: 'Shahlo Karimova',
    role: {
      uz: 'Bosh Mikrobiolog & Laboratoriya Rahbari',
      ru: 'Главный микробиолог и зав. лабораторией',
      en: 'Head Microbiologist & Lab Director',
    },
    bio: {
      uz: 'Har bir partiya mahsulotning tozaligi va biologik xavfsizligini ta\'minlovchi ISO sertifikatlangan ekspert.',
      ru: 'Эксперт по стандарту ISO, отвечающий за безупречную биологическую чистоту и безопасность каждой партии.',
      en: 'Certified ISO expert supervising strict microbiological safety and hygiene testing protocols.',
    },
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'team-3',
    name: 'Alisher Qodirov',
    role: {
      uz: 'Bosh Zooveterinar',
      ru: 'Главный ветеринарный врач',
      en: 'Chief Veterinary Officer',
    },
    bio: {
      uz: 'Fermamizdagi Golshtin-Friz zotli sigirlarning organik oziqlanishi va salomatligi uchun mas\'ul mutaxassis.',
      ru: 'Отвечает за здоровье, сбалансированное органическое питание и комфорт коров на эко-ферме.',
      en: 'Oversees herd health, comfort welfare, and 100% natural organic grass-fed diets.',
    },
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'team-4',
    name: 'Malika Umarova',
    role: {
      uz: 'Mahsulot Dizayneri & R&D Menejeri',
      ru: 'R&D менеджер и разработчик рецептур',
      en: 'Dairy R&D Manager & Food Stylist',
    },
    bio: {
      uz: 'Yangi mevali yogurtlar, pishloqlar va foydali biologik faol qatiq formulalarini yaratuvchi mutaxassis.',
      ru: 'Разработчик новых линеек натуральных йогуртов, полезных био-заквасок и традиционных сыров.',
      en: 'Designs innovative natural dairy recipes, active bio-yogurt ferments, and artisanal cheeses.',
    },
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
  },
];
